apiVersion: v1
kind: ConfigMap
metadata:
  name: green-scheduler-extender-config
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: green-scheduler
    extenders:
      - urlPrefix: http://green-scheduler-webhook:5000/api/scheduler
        filterVerb: filter
        prioritizeVerb: prioritize
        weight: 1
        enableHttps: false